### ISSUE TITLE
Need <server.name> tag

### ISSUE THREAD

**Issue by Talamar1** [DenizenScript/Depenizen-For-Bungee#5]
Need a tag to determine the current server name. mcmonkey suggested `<server.server.name>` because he's weird.

**Comment by mcmonkey4eva** [comment]
I suggested `<server.server>` you mean. That returns a dServer.

**Comment by mcmonkey4eva** [comment]
I think this was added.

Either way, it should've been in https://github.com/DenizenScript/Depenizen-For-Bukkit/issues
